### ISSUE TITLE
activate debug layer

### ISSUE THREAD

**Issue by Bloodwyn** [Kaddah/GaussianSplatting#1]

**Comment by Kaddah** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/d3d12sdklayers/nf-d3d12sdklayers-id3d12debug-enabledebuglayer
https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/direct3d12/directx-12-programming-environment-set-up.md

@vollkornholztuer

**Comment by Kaddah** [comment]
done by marco

**Comment by Bloodwyn** [comment]
test it by making mistake

**Comment by Bloodwyn** [comment]
add #ifndef NDEBUG

**Comment by Kaddah** [comment]
ifndef eingefügt
