### ISSUE TITLE
parse ply files

### ISSUE THREAD

**Issue by Kaddah** [Kaddah/GaussianSplatting#10]
-integrieren von ply Dateien
-zeichnen von Punktwolken im Fenster

**Comment by MacRosefield** [comment]
Import de PLY daten mittels class PlyReader -> Vertex struct vec3 pos; vec3 normale; vec3 color:

Beispiel ergebnis auf cout:
Vertex 11711:
  Position: (0, 0, 5.87173e-39)
  Normale: (0, 2.47588e+27, -0.224851)
  Color: (0, 0, 0)
Vertex 11712:
  Position: (1.7681e-22, -8.30622e-26, -0.133057)
  Normale: (1.05226e-34, 6.88332e-41, 0)
  Color: (0, 0, 0)
Vertex 11713:
  Position: (0, 2.29365e-41, 0)
  Normale: (5.91097e+16, -2.64349e-11, 6.75452e-34)
  Color: (0, 0, 0)
Vertex 11714:
  Position: (-6.39306e+37, -1.17756e+08, -1.06926e+21)
  Normale: (2.67648e-43, 0, 0)
  Color: (0, 0, 0)
Vertex 11715:
  Position: (8.82818e-44, 0, 1.45084e-05)
  Normale: (-3.25097e-38, -2.251, 2.28104e+25)
  Color: (0, 0, 0)
Vertex 11716:
  Position: (-3.15567e-38, 1.94311, 0)
  Normale: (0, 0, 1.875)
  Color: (0, 0, 0);

**Transfer zu VertexBuffer inProgress**

**Comment by Bloodwyn** [comment]
Passt, hatte noch ein \n\r line ending problem, besprechen wir morgen

**Comment by Bloodwyn** [comment]
Test binary vs ASCII, e.g., with Blender

**Comment by MacRosefield** [comment]
Add Gaussian splatt values to struct while importing

**Comment by MacRosefield** [comment]
PlyReader adds spherical harmonics values in vertex struct 
struct Vertex {
    glm::vec3 pos; // Position double x, y, z;
    glm::vec3 normal; // Normale double nx, ny, nz;
    glm::vec4 color; // Farben (8-Bit RGB) unsigned char r, g, b;
    float              opacity;        // Opazität
    glm::vec3          scale;          // Skalierung
    glm::vec4          rotation;       // Rotation
    float f_rest[48]; // Platz für zusätzliche Eigenschaften
    
};
