### ISSUE TITLE
visualize point cloud

### ISSUE THREAD

**Issue by Kaddah** [Kaddah/GaussianSplatting#12]
-Methode integrieren 
Input = Punktwolke -> Dreiecke generieren/zeichnen/visualisieren

**Comment by vollkornholztuer** [comment]
[Siehe dies](https://github.com/Kaddah/GaussianSplatting/issues/10)

**Comment by MacRosefield** [comment]
Einbau Geometrie shader zur visualisierung von dreiecken mit orientierung zur camera

**Comment by Bloodwyn** [comment]
Some points seem to be missing, check with PIX what is happening there.
