### ISSUE TITLE
abstract window into class

### ISSUE THREAD

**Issue by Bloodwyn** [Kaddah/GaussianSplatting#13]
class Window{
  Window(); // init d3d
  virtual void draw();
};

class GaussianRenderer : public Window{
 void draw() override;
}

**Comment by vollkornholztuer** [comment]
tutorial i used:
https://www.youtube.com/watch?v=yfYOm0q_rJQ&list=PLD3tf_aBsga1A9B7UoDkM-yObxlLh9pku&index=3

reference (tutorial followed by me, everything SHOULD work):
https://github.com/vollkornholztuer/DirectX12Framework/tree/64116bf63fd9cdaa101e56ff59d10be0633896fc

**Comment by Kaddah** [comment]
nicht geschafft, da tutorial code sehr linear ist und ich noch nicht ganz drüber steige wie ich den code am besten abstrahiere. großteil ist getan, es hört beim Dreieck auf. :(

**Comment by Kaddah** [comment]
Man kann initialize zeugs aus der mainloop zb in den konstruktor (bevor mainloop aufgerufen wird)
