### ISSUE TITLE
understand and play around with spherical harmonics

### ISSUE THREAD

**Issue by Bloodwyn** [Kaddah/GaussianSplatting#18]

**Comment by Kaddah** [comment]
https://mathworld.wolfram.com/SphericalHarmonic.html
https://en.wikipedia.org/wiki/Table_of_spherical_harmonics
https://de.wikipedia.org/wiki/Kugelkoordinaten
berechnung spherical harmonics

**Comment by Kaddah** [comment]
Vertex shader -> worldcoordinates weitergeben (worldpos = input.pos)
Berechnung farbe in vertex shader -> farbe weitergeben
Camerapos irgendwo in rot matrix
Color = sh.color
Float sh[45]
Funktion von original paper
