### ISSUE TITLE
Geometry Shader

### ISSUE THREAD

**Issue by Kaddah** [Kaddah/GaussianSplatting#21]
Gibst du ein Dreieck rein, kommt auch wieder ein Dreieck raus. -_Weisheit von Basti_

**Comment by adriadri6972** [comment]
initial GeometryShader.hlsl and render each point as splatting

**Comment by MacRosefield** [comment]
-correct geoshader to draw fans on the screen not only circles. 
-reduce geoschader to 16 vertices
-control fan with width and height

**Comment by Bloodwyn** [comment]
![grafik](https://github.com/Kaddah/GaussianSplatting/assets/5436000/be7468d4-694b-4d22-b790-d02f52341489)
