### ISSUE TITLE
macro for errors

### ISSUE THREAD

**Issue by Kaddah** [Kaddah/GaussianSplatting#6]
-exceptions

**Comment by MacRosefield** [comment]
#ifndef ThrowIfFailed
#define ThrowIfFailed(x)                                              \
{                                                                     \
    HRESULT hr__ = (x);                                               \
    std::wstring wfn = AnsiToWString(__FILE__);                       \
    if(FAILED(hr__)) { throw DxException(hr__, L#x, wfn, __LINE__); } \
}
#endif
