### ISSUE TITLE
C++ exceptions

### ISSUE THREAD

**Issue by Kaddah** [Kaddah/GaussianSplatting#8]
-siehe macros

**Comment by MacRosefield** [comment]
Folgende Datein hinzufgefügt:

- DxException.h
- DxException.cpp

###########################
//MACRO FÜR EXCEPTIONS
#ifndef ThrowIfFailed
#define ThrowIfFailed(x) \
{ \
    HRESULT hr__ = (x); \
    std::wstring wfn = AnsiToWString(__FILE__); \
    if (FAILED(hr__)) { throw DxException(hr__, L#x, wfn, __LINE__); } \
}
#endif
###########################

prüft HRESULT und wirft Exception"

Die beiden Funktionen geben Fehlermeldung aus:
###########################
DxException::DxException(HRESULT hr, const std::wstring& functionName, const std::wstring& filename, int lineNumber)
    : ErrorCode(hr), FunctionName(functionName), Filename(filename), LineNumber(lineNumber) {}

const char* DxException::what() const noexcept {
    whatBuffer = "Error in " + std::string(FunctionName.begin(), FunctionName.end()) +
        " in file " + std::string(Filename.begin(), Filename.end()) +
        " at line " + std::to_string(LineNumber);
    return whatBuffer.c_str();
}
#############################

Funktionsaufrufe mit Dx werden von nun als Parameter des MAKROS aufgerufen
########################
ThrowIfFailed(SimulateDirectXFunction());
########################
